version: '3.8'
services:
 mysqldb:
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   env_file: ./.env
   environment:
     - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
     - MYSQL_DATABASE=$MYSQLDB_DATABASE
   ports:
     - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
   volumes:
     - db:/var/lib/mysql
     - ./init:/docker-entrypoint-initdb.d
   networks:
      default:
        aliases:
          - mysqldb
 app:
   depends_on:
     - mysqldb
   build: ./server
   restart: unless-stopped
   env_file: ./.env
   ports:
     - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
   environment:
     - DB_HOST=mysqldb
     - DB_USER=$MYSQLDB_USER
     - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
     - DB_NAME=$MYSQLDB_DATABASE
     - DB_PORT=$MYSQLDB_DOCKER_PORT
   stdin_open: true
   tty: true
   networks:
      default:
        aliases:
          - app
 frontend:
   depends_on:
     - app
   build: ./client
   restart: unless-stopped
   ports:
     - 3000:3000
   stdin_open: true
   tty: true
   networks:
      default:
        aliases:
          - frontend

volumes: 
 db: